[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/speak"
  to = "/.netlify/functions/speak"
  status = 200

[[redirects]]
  from = "/api/places"
  to = "/.netlify/functions/places"
  status = 200

[[redirects]]
  from = "/api/notify"
  to = "/.netlify/functions/notify"
  status = 200

[functions]
  node_bundler = "esbuild"

[[scheduled_functions]]
  function = "notify"
  schedule = "0 * * * *"

[[redirects]]
  from = "/api/vision"
  to = "/.netlify/functions/vision"
  status = 200
